export { default as HeroSection } from './HeroSection'
export { default as CoursesSection } from './CoursesSection'
export { default as AITutorSection } from './AITutorSection'
export { default as ActiveLearningSection } from './ActiveLearningSection'
export { default as AnalyticsSection } from './AnalyticsSection'
export { default as CertificateSection } from './CertificateSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as AcademyPromosSection, default as UdemyPromosSection } from './UdemyPromosSection'
export { default as FinalCTASection } from './FinalCTASection'
